alias: 'bedtime: Restore variables at night'
description: ''
trigger:
  - platform: time
    at: '00:00:00'
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.extender_shed
mode: single
